import { z } from 'zod';

type SpcsZoneType = 'lcc' | 'tm';

export const SpcsZoneTypeDef: { [key in SpcsZone]: SpcsZoneType } = {
	'AR-North': 'lcc',
	'AR-South': 'lcc',
	'CA-401': 'lcc',
	'CA-402': 'lcc',
	'CA-403': 'lcc',
	'CA-404': 'lcc',
	'CA-405': 'lcc',
	'CA-406': 'lcc',
	'CO-Central': 'lcc',
	'CO-North': 'lcc',
	'CO-South': 'lcc',
	'CT-600': 'lcc',
	'FL-North': 'lcc',
	'IA-North': 'lcc',
	'IA-South': 'lcc',
	'KS-North': 'lcc',
	'KS-South': 'lcc',
	'KY-North': 'lcc',
	'KY-South': 'lcc',
	'LA-North': 'lcc',
	'LA-Offshore': 'lcc',
	'LA-South': 'lcc',
	'MA-Island': 'lcc',
	'MA-Mainland': 'lcc',
	'MD-1900': 'lcc',
	'MI-Central': 'lcc',
	'MI-North': 'lcc',
	'MI-South': 'lcc',
	'MN-Central': 'lcc',
	'MN-North': 'lcc',
	'MN-South': 'lcc',
	'MT-2500': 'lcc',
	'NC-3200': 'lcc',
	'ND-North': 'lcc',
	'ND-South': 'lcc',
	'NE-2600': 'lcc',
	'NY-Long Island': 'lcc',
	'OH-North': 'lcc',
	'OH-South': 'lcc',
	'OK-North': 'lcc',
	'OK-South': 'lcc',
	'OR-North': 'lcc',
	'OR-South': 'lcc',
	'PA-North': 'lcc',
	'PA-South': 'lcc',
	'PR VI-5200': 'lcc',
	'SC-3900': 'lcc',
	'SD-North': 'lcc',
	'SD-South': 'lcc',
	'TN-4100': 'lcc',
	'TX-Central': 'lcc',
	'TX-North': 'lcc',
	'TX-North Central': 'lcc',
	'TX-South': 'lcc',
	'TX-South Central': 'lcc',
	'UT-Central': 'lcc',
	'UT-North': 'lcc',
	'UT-South': 'lcc',
	'VA-North': 'lcc',
	'VA-South': 'lcc',
	'WA-North': 'lcc',
	'WA-South': 'lcc',
	'WI-Central': 'lcc',
	'WI-North': 'lcc',
	'WI-South': 'lcc',
	'WV-North': 'lcc',
	'WV-South': 'lcc',
	'AK-5001/O.M.': 'tm',
	'AK-5002': 'tm',
	'AK-5003': 'tm',
	'AK-5004': 'tm',
	'AK-5005': 'tm',
	'AK-5006': 'tm',
	'AK-5007': 'tm',
	'AK-5008': 'tm',
	'AK-5009': 'tm',
	'AL-East': 'tm',
	'AL-West': 'tm',
	'AZ-Central': 'tm',
	'AZ-East': 'tm',
	'AZ-West': 'tm',
	'DE-700': 'tm',
	'FL-East': 'tm',
	'FL-West': 'tm',
	'GA-East': 'tm',
	'GA-West': 'tm',
	'HI-5101': 'tm',
	'HI-5102': 'tm',
	'HI-5103': 'tm',
	'HI-5104': 'tm',
	'HI-5105': 'tm',
	'ID-Central': 'tm',
	'ID-East': 'tm',
	'ID-West': 'tm',
	'IL-East': 'tm',
	'IL-West': 'tm',
	'IN-East': 'tm',
	'IN-West': 'tm',
	'ME-East': 'tm',
	'ME-West': 'tm',
	'MO-Central': 'tm',
	'MO-East': 'tm',
	'MO-West': 'tm',
	'MS-East': 'tm',
	'MS-West': 'tm',
	'NH-2800': 'tm',
	'NJ/NY East-2900': 'tm',
	'NM-Central': 'tm',
	'NM-East': 'tm',
	'NM-West': 'tm',
	'NV-Central': 'tm',
	'NV-East': 'tm',
	'NV-West': 'tm',
	'NY-Central': 'tm',
	'NY-East': 'tm',
	'NY-West': 'tm',
	'RI-3800': 'tm',
	'VT-4400': 'tm',
	'WY-East': 'tm',
	'WY-East Central': 'tm',
	'WY-West': 'tm',
	'WY-West Central': 'tm',
};

export const SpcsZoneSchema = z.enum([
	'AK-5001/O.M.',
	'AK-5002',
	'AK-5003',
	'AK-5004',
	'AK-5005',
	'AK-5006',
	'AK-5007',
	'AK-5008',
	'AK-5009',
	'AL-East',
	'AL-West',
	'AR-North',
	'AR-South',
	'AZ-Central',
	'AZ-East',
	'AZ-West',
	'CA-401',
	'CA-402',
	'CA-403',
	'CA-404',
	'CA-405',
	'CA-406',
	'CO-Central',
	'CO-North',
	'CO-South',
	'CT-600',
	'DE-700',
	'FL-East',
	'FL-North',
	'FL-West',
	'GA-East',
	'GA-West',
	'HI-5101',
	'HI-5102',
	'HI-5103',
	'HI-5104',
	'HI-5105',
	'IA-North',
	'IA-South',
	'ID-Central',
	'ID-East',
	'ID-West',
	'IL-East',
	'IL-West',
	'IN-East',
	'IN-West',
	'KS-North',
	'KS-South',
	'KY-North',
	'KY-South',
	'LA-North',
	'LA-Offshore',
	'LA-South',
	'MA-Island',
	'MA-Mainland',
	'MD-1900',
	'ME-East',
	'ME-West',
	'MI-Central',
	'MI-North',
	'MI-South',
	'MN-Central',
	'MN-North',
	'MN-South',
	'MO-Central',
	'MO-East',
	'MO-West',
	'MS-East',
	'MS-West',
	'MT-2500',
	'NC-3200',
	'ND-North',
	'ND-South',
	'NE-2600',
	'NH-2800',
	'NJ/NY East-2900',
	'NM-Central',
	'NM-East',
	'NM-West',
	'NV-Central',
	'NV-East',
	'NV-West',
	'NY-Central',
	'NY-East',
	'NY-Long Island',
	'NY-West',
	'OH-North',
	'OH-South',
	'OK-North',
	'OK-South',
	'OR-North',
	'OR-South',
	'PA-North',
	'PA-South',
	'PR VI-5200',
	'RI-3800',
	'SC-3900',
	'SD-North',
	'SD-South',
	'TN-4100',
	'TX-Central',
	'TX-North',
	'TX-North Central',
	'TX-South',
	'TX-South Central',
	'UT-Central',
	'UT-North',
	'UT-South',
	'VA-North',
	'VA-South',
	'VT-4400',
	'WA-North',
	'WA-South',
	'WI-Central',
	'WI-North',
	'WI-South',
	'WV-North',
	'WV-South',
	'WY-East',
	'WY-East Central',
	'WY-West',
	'WY-West Central',
]);
export type SpcsZone = z.infer<typeof SpcsZoneSchema>;
